[project]
name = "technical-analysis-mcp"
version = "0.1.0"
description = "MCP server for technical analysis using yfinance"
authors = [{ name = "Alejandro Claro", email = "alejandro.claro@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "fastmcp>=2.14.3",
  "yfinance>=1.0",
  "pytest>=9.0.2",
  "pytest-asyncio>=1.3.0",
  "uvicorn>=0.40.0",
  "pymarkdownlnt>=0.9.34",
  "PyHamcrest>=2.1.0",
]

[project.optional-dependencies]
dev = [
  "ruff>=0.14.13",
  "pyright>=1.1.408",
  "pymarkdownlnt>=0.9.34",
]

[project.scripts]
server = "technical_analysis_mcp.server:main"

[tool.pyright]
venvPath = "."
venv = ".venv"

exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "build",
  "dist"
]

[tool.ruff]
line-length = 120
select = ["ALL"]

exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "build",
  "dist"
]
