[tool.poetry]
name = "technical-analysis-mcp"
version = "0.1.0"
description = "MCP server for technical analysis using yfinance"
authors = ["Alejandro Claro <alejandro.claro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastmcp = "^2.14.3"
yfinance = "^1.0"
pytest = "^9.0.2"
pytest-asyncio = "^1.3.0"
uvicorn = "^0.40.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.13"
pyright = "^1.1.408"
pymarkdownlnt = "^0.9.34"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
server = "src.technical_analysis_mcp.server:main"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType = false

venvPath = "."
venv = ".venv"

exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "build",
  "dist"
]

[tool.ruff]
line-length = 120
select = ["ALL"]

exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "build",
  "dist"
]
